name: mpma
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - ca-certificates=2024.9.24=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.9.20=he870216_1
  - python_abi=3.9=2_cp39
  - pyzmq=25.1.2=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - audioread==3.0.1
      - beautifulsoup4==4.12.3
      - bert-score==0.3.13
      - bitsandbytes==0.44.1
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.0.2
      - dill==0.3.8
      - distro==1.9.0
      - evaluate==0.4.3
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google==3.0.0
      - google-api-core==2.24.0
      - google-api-python-client==2.155.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.66.0
      - h11==0.14.0
      - httpcore==1.0.8
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.26.0
      - idna==3.10
      - ijson==3.3.0
      - importlib-resources==6.4.5
      - inquirerpy==0.3.4
      - jinja2==3.1.3
      - jiter==0.9.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - opacus==1.5.4
      - openai==1.75.0
      - openattack==2.1.1
      - opt-einsum==3.4.0
      - pandas==2.2.3
      - peft==0.13.2
      - pfzy==0.3.4
      - pillow==10.2.0
      - pip==24.3.1
      - pooch==1.8.2
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pynvml==12.0.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rouge-score==0.1.2
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.20.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.66.6
      - transformers==4.46.1
      - triton==3.1.0
      - typing-inspection==0.4.0
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.17.1
      - zipp==3.21.0
prefix: /home/yourname/envs/mpma
